FIGS= plaque.eps plaque2.eps essailed.eps essaiint.eps \
	montageou.eps montageou2.eps  porteou.eps \
	porteet.eps montageet.eps


%.pdf: %.tex
	xelatex  $<
	xelatex  $<

tdarchi1.pdf: tdarchi1.tex $(FIGS)

