execs = adresse-pointeur annee arith bug chainages
execs += fonctionnelle malloc-overhead parcours
execs += pointeurs-fonctions retour stacks
execs += stock tableau-actions tableau-extensible tailles typecast


CFLAGS += -Wall -Wextra -std=c17

all: $(execs)

clean:
	$(RM) *~

mrproper: clean
	$(RM) $(execs)
