CFLAGS += -std=c11
CFLAGS += -Wall -Wextra -Wno-unused 

execs = adresse-pointeur annee arith bug chainages fonctionnelle malloc-overhead parcours pointeurs-fonctions retour stacks stock tableau-actions tableau-extensible tailles typecast



all: $(execs)


clean:
	$(RM) *.o *~

mrproper: clean
	$(RM) $(execs)
