PARTS = livret.md
PARTS +=	part-introduction.md
PARTS +=	part-rappels.md
PARTS +=	chap-rappels.md
PARTS +=	chap-pointeurs.md
PARTS +=	chap-allocation.md
PARTS +=	part-conteneurs.md
PARTS +=	chap-tableaux-extensibles.md
PARTS +=	chap-ensemble-chaines.md

%.md: %.tex
	pandoc -N --toc -o $@ $<

livret.html: $(PARTS)
	pandoc -t html -o $@ $^
