HTMLDIR = ../Output
PDFDIR = ../Output
EBOOKSDIR = ../Output


ALL = 10-introduction 20-temps-partage 30-memoire
ALL += 40-stockage-permanent

PDF1COL = $(ALL)
EBOOKS =  $(ALL)
HTMLPAGES = $(ALL)

include ../lib/common5.mk






