HTMLDIR = ../Output
PDFDIR = ../Output
EBOOKSDIR = ../Output


EBOOKS = circuits-logiques
HTMLPAGES = circuits-logiques
PDF1COL = circuits-logiques

PARTS = circuits-logiques.md
PARTS += codages.md
PARTS += elements-technologie.md
PARTS += algebre-boole.md
PARTS += circuits-combinatoires.md
PARTS += circuits-sequentiels.md


include ../lib/common5.mk


../Output/circuits-logiques.pdf: circuits-logiques.meta $(PARTS)
../Output/circuits-logiques.epub: circuits-logiques.meta $(PARTS)
../Output/circuits-logiques.html: circuits-logiques.meta $(PARTS)
